#ifndef USER_CONFIG_H
#define USER_CONFIG_H

#define FIRMWARE_VERSION "1.0.0"

#define EPD_SPI_NUM SPI2_HOST
#define ESP32_I2C_DEV_NUM I2C_NUM_0

#define EPD_WIDTH 200
#define EPD_HEIGHT 200

/* EPD ports (SPI2) */
#define EPD_DC_PIN GPIO_NUM_10
#define EPD_CS_PIN GPIO_NUM_11
#define EPD_SCK_PIN GPIO_NUM_12
#define EPD_MOSI_PIN GPIO_NUM_13
#define EPD_RST_PIN GPIO_NUM_9
#define EPD_BUSY_PIN GPIO_NUM_8

/* DEV POWER init */
#define EPD_PWR_PIN GPIO_NUM_6
#define Audio_PWR_PIN GPIO_NUM_42
#define VBAT_PWR_PIN GPIO_NUM_17

#define BOOT_BUTTON_PIN GPIO_NUM_0
#define PWR_BUTTON_PIN GPIO_NUM_18

/* Low-power wake-up */
#define ext_wakeup_pin_1 GPIO_NUM_0

/* ESP32 I2C Init */
#define ESP32_I2C_SDA_PIN GPIO_NUM_47
#define ESP32_I2C_SCL_PIN GPIO_NUM_48

/* LVGL init */
#define LVGL_BUF_PIXELS (EPD_WIDTH * EPD_HEIGHT)
#define LVGL_SPIRAM_BUFF_LEN (LVGL_BUF_PIXELS * 2)
#define EXAMPLE_LVGL_TICK_PERIOD_MS 5
#define EXAMPLE_LVGL_TASK_MAX_DELAY_MS 500
#define EXAMPLE_LVGL_TASK_MIN_DELAY_MS 100

/* I2C devices */
#define I2C_RTC_DEV_Address 0x51
#define I2C_SHTC3_DEV_Address 0x70
#define I2C_FT6336_DEV_Address 0x38

/* Touch (FT6336) */
#define EPD_TP_RST_PIN GPIO_NUM_7
#define EPD_TP_INT_PIN GPIO_NUM_21

/* WiFi */
#define WIFI_SSID "MY_WIFI_SSID"
#define WIFI_PASSWORD "MY_WIFI_PASSWORD"

/* API */
#define API_BASE_URL "MY_API_BASE_URL"

/* Deep Sleep */
#define INACTIVITY_TIMEOUT_MS 60000
#define SLEEP_DURATION_SEC 3600

/* WebSocket */
#define WS_REQUEST_TIMEOUT_MS 600000

#endif
